
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int MOD = 8;
  public static final int DEUX_POINTS = 10;
  public static final int PLUS = 4;
  public static final int INT = 18;
  public static final int SUP = 12;
  public static final int RPAREN = 3;
  public static final int IDENTIFIER = 17;
  public static final int POINT_INTERROGATION = 9;
  public static final int LPAREN = 2;
  public static final int INF = 11;
  public static final int INF_EGAL = 13;
  public static final int EOF = 0;
  public static final int DIV = 7;
  public static final int DOUBLE_EGAL = 15;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int SUP_EGAL = 14;
  public static final int INEGAL = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "POINT_INTERROGATION",
  "DEUX_POINTS",
  "INF",
  "SUP",
  "INF_EGAL",
  "SUP_EGAL",
  "DOUBLE_EGAL",
  "INEGAL",
  "IDENTIFIER",
  "INT"
  };
}

